ci: add newline linter
In review of #426, a reviewer caught that a file was missing a newline
at the end. This will save humans from having to point this out in the
future.

For now it's running only in existing workflows so it doesn't eat
additional github actions minutes. That means if a commit only changes
files not checked by these workflows (.github/* and */*.py), they will
get missed.

Signed-off-by: Russell Bryant <rbryant@redhat.com>

diff --git a/.github/workflows/actionlint.yml b/.github/workflows/actionlint.yml
--- a/.github/workflows/actionlint.yml
+++ b/.github/workflows/actionlint.yml
@@ -26,3 +26,6 @@ jobs:
         run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
       - name: Check workflow files
         run: PATH=".:$PATH" actionlint -color
+      - name: Check for trailing newline characters
+        id: newline-check
+        run: git ls-files -z | while IFS= read -rd '' f; do if file --mime-encoding "$f" | grep -qv binary; then tail -c1 < "$f" | read -r _ || (echo "$f is missing a trailing newline." && touch .newlines-missing) ; fi; done; [ ! -f .newlines-missing ] || exit 1
